//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_OneProEjemplo
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallePedido
    {
        public int idDetalle { get; set; }
        public int idPedido { get; set; }
        public int idArticulo { get; set; }
        public Nullable<double> cantidad { get; set; }
        public Nullable<decimal> total { get; set; }
    
        public virtual Articulo Articulo { get; set; }
        public virtual Pedido Pedido { get; set; }
    }
}
