//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_OneProEjemplo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direccion
    {
        public int idDireccion { get; set; }
        public int idCliente { get; set; }
        public string direccion1 { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
